api_platform:
    title: 'Ways To Go'
    description: 'API for Ways To Go'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    collection:
        pagination:
            enabled: false
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    eager_loading:
        force_eager: false