register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: POST

login_check:
    path:     /login_check
    methods:  [POST]

trips_cities:
    path:     /api/trips/cities
    controller: App\Controller\TripController::getCities
    methods:  GET

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui